// Generated by CoffeeScript 1.6.3
(function() {
  var classComplement, classSpecsHandler, classes, complement, defaultUnitFrame, resetInviter, roleHandler, showRoles, specComplement, specRolesHandler, specs;

  classes = ["warrior", "paladin", "deathknight", "shaman", "hunter", "druid", "rogue", "mage", "priest", "warlock"];

  specs = {
    "warrior": ['fury', 'arms', 'prot'],
    "paladin": ['prot', 'holy', 'ret'],
    "deathknight": ['blood', 'frost', 'unholy'],
    "shaman": ['ele', 'enhancement', 'resto'],
    "hunter": ['bm', 'mm', 'survival'],
    "druid": ['balance', 'feral', 'resto'],
    "rogue": ['assassin', 'combat', 'subtlety'],
    "mage": ['arcane', 'fire', 'frost'],
    "priest": ['disc', 'holy', 'shadow'],
    "warlock": ['aff', 'demo', 'destro']
  };

  defaultUnitFrame = {
    'display': 'block',
    'backgroundColor': '#111',
    'fontWeight': 'normal'
  };

  complement = function(element, array) {
    var comp, e, _i, _len;
    comp = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      e = array[_i];
      if (e !== element) {
        comp.push(e);
      }
    }
    return comp;
  };

  classComplement = function(klass) {
    return complement(klass, classes);
  };

  specComplement = function(klass, spec) {
    return complement(spec, specs[klass]);
  };

  showRoles = function(klass, spec) {
    var hide, show;
    show = function(role) {
      return $(".roles div." + role).show();
    };
    hide = function(role) {
      return $(".roles div." + role).hide();
    };
    if (spec === "holy" || spec === "disc" || spec === "resto") {
      show('heal');
      hide('tank');
      hide('dps');
    } else if (spec === "prot") {
      show('tank');
      hide('dps');
      hide('heal');
    } else if (spec === "feral" || spec === "unholy" || spec === "blood") {
      show('tank');
      show('dps');
      hide('heal');
    } else {
      show('dps');
      hide('tank');
      hide('heal');
    }
    if (spec === "frost") {
      if (klass === "mage") {
        show('dps');
        hide('tank');
        return hide('heal');
      } else {
        show('dps');
        show('tank');
        return hide('heal');
      }
    }
  };

  classSpecsHandler = function(klass) {
    return $(".classes ." + klass).click(function() {
      var c, _i, _len, _ref;
      if (!$(this).hasClass('selected')) {
        $('.roles div').hide();
        $('.specs div span').removeClass('selected');
        $('.info span.spec').text("");
        $('.info span.role').text("");
        $("#ok").hide();
      }
      $(this).addClass('selected');
      _ref = classComplement(klass);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        c = _ref[_i];
        $(".classes ." + c).removeClass('selected');
        $(".specs ." + c).hide();
      }
      $(".specs ." + klass).show();
      return $('.info span.klass').text(klass);
    });
  };

  specRolesHandler = function(klass, spec) {
    return $(".specs ." + klass + " ." + spec).click(function() {
      var c, _i, _len, _ref;
      if (!$(this).hasClass('selected')) {
        $('.roles span').removeClass('selected');
        $('.info span.role').text("");
        $('#ok').hide();
      }
      $(this).addClass('selected');
      _ref = specComplement(klass, spec);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        c = _ref[_i];
        $(".specs ." + c).removeClass('selected');
      }
      showRoles(klass, spec);
      return $('.info span.spec').text(spec);
    });
  };

  roleHandler = function(role) {
    return $(".roles ." + role + " span").click(function() {
      var other, _i, _len, _ref;
      $(this).addClass('selected');
      _ref = ["dps", "tank", "heal"];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        other = _ref[_i];
        if (other !== role) {
          $(".roles ." + other + " span").removeClass('selected');
        }
      }
      $(".info span.role").text(role);
      return $('#ok').show();
    });
  };

  resetInviter = function() {
    return $('#reset').click(function() {
      event.preventDefault();
      $('#ok').hide();
      $(".roles div").hide();
      $(".specs div").hide();
      $(".classes span").removeClass('selected');
      return $('span.spec, span.klass, span.role').text("");
    });
  };

  $(function() {
    var klass, role, spec, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1;
    for (_i = 0, _len = classes.length; _i < _len; _i++) {
      klass = classes[_i];
      classSpecsHandler(klass);
    }
    for (_j = 0, _len1 = classes.length; _j < _len1; _j++) {
      klass = classes[_j];
      _ref = specs[klass];
      for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
        spec = _ref[_k];
        specRolesHandler(klass, spec);
      }
    }
    _ref1 = ["dps", "tank", "heal"];
    for (_l = 0, _len3 = _ref1.length; _l < _len3; _l++) {
      role = _ref1[_l];
      roleHandler(role);
    }
    return resetInviter();
  });

}).call(this);
